In [5]:
import pandas as pd
import numpy as np
import json

In [6]:
def processa_colunas(df):
    
    #####   traduz campos das colunas categ√≥ricas
    coluna = "employment__type"
    dic_troca = {'labourer': 'operario', 'professional':'nivel medio', 'unemployed':'desempregado', 'management': 'nivel alto'}
    df.replace({coluna: dic_troca},inplace=True)      
    
    coluna = "finance__accounts__checking__balance"
    dic_troca = {'no_account':'sem conta', 'low' : 'baixa', 'negative' : 'negativa', 'high' : 'alta'}
    df.replace({coluna: dic_troca},inplace=True)
    
    coluna= 'finance__accounts__savings__balance'
    dic_troca = {'very_high': 'muito_alta' ,'low': 'baixa' , 'high': 'alta' , 'medium': 'media',  'no_account': 'sem conta'}
    df.replace({coluna: dic_troca},inplace=True)
    
    coluna= 'contact__has_telephone'
    dic_troca = {False: 'Nao' ,True: 'Sim' }
    df.replace({coluna: dic_troca},inplace=True)
    
    coluna= 'finance__repayment_history'
    dic_troca = {'very_poor': 'muito pobre' ,'good': 'boa','poor': 'pobre' }
    df.replace({coluna: dic_troca},inplace=True)
    
    coluna=  'finance__other_assets'
    dic_troca = {'real_estate': 'imovel' ,'car_or_other': 'carro ou outro','life_insurance': 'seguro de vida', 'none' : 'Nao'  }
    df.replace({coluna: dic_troca},inplace=True)

    coluna=  'credit__purpose'
    dic_troca = {  'new_car': 'carro novo' ,'electronics': 'eletronico','re-training': 'requalificacao', 'appliances' : 'eletrodomestico',
            'education' : 'educacao',   'business'   : 'empresa',       'repairs': 'reformas',         'furniture': 'mobiliario',
             'used_car' :'carro_usado' ,     'other' : 'outro' }
    df.replace({coluna: dic_troca},inplace=True)
    
    coluna=  'residence__type'
    dic_troca = {'own': 'proprio' ,'rent': 'aluguel','free': 'gratis'  }
    df.replace({coluna: dic_troca},inplace=True)
    
    ##  multiplica a quantia por 6 --- converte para real
    df['credit__amount'] = df['credit__amount']*6
    
    ## dropa colunas
    df.drop(to_drop, axis=1,inplace=True)
    
    ### troca nome das colunas
    df.rename(columns=dic_traducao,inplace=True)
    return df

In [7]:
### COLUNAS PARA DROP 
to_drop = ['employment__permit',]

In [9]:
dic_traducao = {    'credit__coapplicant' : 'credito_coaplicante',                  'credit__guarantor'  : 'credito_fiador',
         'finance__credits__other_stores' : 'financiamento_outro_lugar',           'employment__permit'  : 'carteira_trabalho',
             'employment__type'           : 'tipo_emprego',   'finance__accounts__checking__balance'     : 'conta_corrente_valor',
     'finance__credits__this_bank'        : 'outros_creditos_aqui',    'finance__credits__other_banks   ': 'credito_outro_lugar',
                'personal__num_dependents': 'numero_dependentes',  'finance__accounts__savings__balance' : 'investimentos_valor',
                    'residence__duration' : 'duracao_residencia',                        'credit__amount': 'valor_solicitado',
                 'contact__has_telephone' : 'tem_telefone',                       'employment__duration' : 'duracao_emprego', 
                       'credit__duration' : 'duracao_credito',              'finance__repayment_history' : 'historico_credito' ,
                  'finance__other_assets' : 'financiamento_outros_bens',               'credit__purpose' : 'proposito_credito',
                        'residence__type' : 'tipo_residencia',                'credit__installment_rate' : 'receita_disponivel' 
              }

##  DATAFRAME DE TREINAMENTO

In [5]:
# # Lista as columns com valores nao numericos
# colunas_cat = ['employment__permit', 'employment__type',
#        'finance__accounts__checking__balance',
#        'finance__accounts__savings__balance', 'contact__has_telephone',
#        'finance__repayment_history', 'finance__other_assets',
#        'credit__purpose', 'residence__type']
# df.select_dtypes(exclude=[np.number]).columns

In [6]:
dic = []
with open("train_data.json") as f:
    for line in f:
        dic.append(json.loads(line))
df = pd.DataFrame.from_dict(dic) 
df = processa_colunas(df)

#Lista todas as colunas
#df.columns

In [7]:
###  LE TRAIN LABELS
dic = []
with open("train_label.json") as f:
    for line in f:
        dic.append(json.loads(line))
df_label = pd.DataFrame.from_dict(dic)      
#df_label.head(10)
coluna=  'credit__default'
dic_troca = {  False: 0 ,True: 1,}
# troca os valores das colunas
df_label.replace({coluna: dic_troca},inplace=True)
# troca o nome da coluna
df_label.rename(columns={'credit__default': 'deu_default'},inplace=True)

In [8]:
###  Junta os dois dataframes em um apenas
df_train = pd.concat([df_label, df], axis=1)
df_train.head(1)

df_train.to_csv('train.csv')

##  DATAFRAME DE TESTES

In [ ]:
# # Lista as columns com valores nao numericos
# colunas_cat = ['employment__permit', 'employment__type',
#        'finance__accounts__checking__balance',
#        'finance__accounts__savings__balance', 'contact__has_telephone',
#        'finance__repayment_history', 'finance__other_assets',
#        'credit__purpose', 'residence__type']
# df.select_dtypes(exclude=[np.number]).columns

In [10]:
dic = []
with open("test_data.json") as f:
    for line in f:
        dic.append(json.loads(line))
df = pd.DataFrame.from_dict(dic) 
df = processa_colunas(df)

#Lista todas as colunas
#df.columns

In [11]:
df.columns

Index(['credito_coaplicante', 'credito_fiador', 'financiamento_outro_lugar',
       'tipo_emprego', 'conta_corrente_valor', 'outros_creditos_aqui',
       'finance__credits__other_banks', 'numero_dependentes',
       'investimentos_valor', 'duracao_residencia', 'valor_solicitado',
       'tem_telefone', 'duracao_emprego', 'duracao_credito',
       'historico_credito', 'financiamento_outros_bens', 'proposito_credito',
       'tipo_residencia', 'receita_disponivel'],
      dtype='object')

In [11]:
###  LE TRAIN LABELS
dic = []
with open("test_label.json") as f:
    for line in f:
        dic.append(json.loads(line))
df_label = pd.DataFrame.from_dict(dic)      
#df_label.head(10)
coluna=  'credit__default'
dic_troca = {  False: 0 ,True: 1,}
# troca os valores das colunas
df_label.replace({coluna: dic_troca},inplace=True)
# troca o nome da coluna
df_label.rename(columns={'credit__default': 'deu_default'},inplace=True)

In [12]:
###  Junta os dois dataframes em um apenas
df_test = pd.concat([df_label, df], axis=1)
df_test.head(1)

df_test.to_csv('test.csv')

In [21]:
df_result =pd.concat([df_train,df_test],axis=0)
df_result.shape

(1000, 20)

In [22]:
df_result.reset_index(inplace=True,drop=True)
df_result

,deu_default,credito_coaplicante,credito_fiador,financiamento_outro_lugar,tipo_emprego,conta_corrente_valor,outros_creditos_aqui,finance__credits__other_banks,numero_dependentes,investimentos_valor,duracao_residencia,valor_solicitado,tem_telefone,duracao_emprego,duracao_credito,historico_credito,financiamento_outros_bens,proposito_credito,tipo_residencia,receita_disponivel
0,0,0,0,0,operario,sem conta,2,1,1,muito_alta,2,1500,Nao,2,6,muito pobre,imovel,carro novo,proprio,2
1,0,0,0,0,operario,baixa,1,0,1,baixa,4,1656,Nao,2,9,boa,imovel,carro novo,aluguel,4
2,0,0,0,0,nivel medio,negativa,2,0,1,alta,4,2028,Nao,15,6,muito pobre,carro ou outro,eletronico,proprio,4
3,0,0,0,0,operario,negativa,1,2,1,baixa,1,2034,Nao,12,12,boa,carro ou outro,requalificacao,proprio,4
4,0,0,0,0,nivel medio,negativa,1,0,1,baixa,1,2058,Nao,1,6,boa,imovel,eletrodomestico,proprio,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,0,0,0,nivel alto,baixa,1,0,1,baixa,2,84162,Sim,5,60,boa,Nao,carro novo,proprio,4
996,1,0,0,0,nivel alto,baixa,1,0,1,baixa,2,85908,Sim,14,36,boa,Nao,carro novo,gratis,4
997,1,0,0,0,nivel alto,baixa,2,2,1,media,4,88692,Sim,10,60,boa,Nao,outro,gratis,3
998,0,0,0,0,nivel medio,sem conta,2,0,1,baixa,4,93918,Sim,5,60,pobre,carro ou outro,eletronico,proprio,2
999,1,0,0,0,nivel medio,baixa,1,0,1,baixa,2,94032,Sim,3,48,boa,carro ou outro,empresa,proprio,2

In [29]:
df_result.to_csv('credito_limpo.csv',index = False, header=False)

In [28]:
df_result.credito_coaplicante.unique()

array([0, 1])

In [27]:
df_result.columns

Index(['deu_default', 'credito_coaplicante', 'credito_fiador',
       'financiamento_outro_lugar', 'tipo_emprego', 'conta_corrente_valor',
       'outros_creditos_aqui', 'finance__credits__other_banks',
       'numero_dependentes', 'investimentos_valor', 'duracao_residencia',
       'valor_solicitado', 'tem_telefone', 'duracao_emprego',
       'duracao_credito', 'historico_credito', 'financiamento_outros_bens',
       'proposito_credito', 'tipo_residencia', 'receita_disponivel'],
      dtype='object')

In [ ]:
###  traducao de campos do dataframe , mas  google rejeita devido tempo/volume

#!pip install google_trans_new
from google_trans_new import google_translator  
translator = google_translator() 
d = {"City_trad_chinese":["È¶ôÊ∏ØÁâπÂà´Ë°åÊîøÂå∫",
                          "Êæ≥Èó®ÁâπÂà´Ë°åÊîøÂå∫",
                          "Âåó‰∫¨Â∏Ç",
                          "‰∏äÊµ∑Â∏Ç"]}
d = {"City_trad_pt" :["S√£o Paulo","Rio de Janeiro"]}

df = pd.DataFrame(data=d)
translator = translator()
df["City_English"] = df["City_trad_pt"].map(lambda x: translator.translate(x, lang_src="pt", lang_tgt="en").text)
df